name: Test Secrets

on:
  push:
    branches:
      - main

jobs:
  test_secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Print Secret
      env:
        SECRET_VALUE: ${{ secrets.TEST }}
      run: echo "The value of MY_SECRET is $SECRET_VALUE"
